(in-package :pseudopod)

(defstruct (file-object (:constructor %make-file-object))
  (id "" :type string)
  (object "file" :type string)
  (filename "" :type string)
  (bytes 0 :type integer)
  (created-at 0 :type integer)
  (purpose nil :type (or null string))
  (status nil :type (or null string))
  (status-details nil)
  (extras nil))

(defun %file-object-integer (value)
  (cond
    ((integerp value) value)
    ((and (stringp value)
          (plusp (length value))
          (every #'digit-char-p value))
     (parse-integer value))
    (t 0)))

(defun %copy-file-object-extras (hash)
  (let ((extras (make-hash-table :test #'equal)))
    (maphash (lambda (key value)
               (unless (member key
                               '("id" "object" "filename" "bytes" "created_at"
                                 "purpose" "status" "status_details")
                               :test #'string=)
                 (setf (gethash key extras) value)))
             hash)
    (when (> (hash-table-count extras) 0)
      extras)))

(defun hash-to-file-object (hash)
  "Deserialize FILE object hash from Moonshot/OpenAI-style Files API."
  (unless (hash-table-p hash)
    (error "Expected file object hash-table, got ~S" hash))
  (%make-file-object
   :id (or (and (stringp (gethash "id" hash))
                (gethash "id" hash))
           "")
   :object (or (and (stringp (gethash "object" hash))
                    (gethash "object" hash))
               "file")
   :filename (or (and (stringp (gethash "filename" hash))
                      (gethash "filename" hash))
                 "")
   :bytes (%file-object-integer (gethash "bytes" hash))
   :created-at (%file-object-integer (gethash "created_at" hash))
   :purpose (and (stringp (gethash "purpose" hash))
                 (gethash "purpose" hash))
   :status (and (stringp (gethash "status" hash))
                (gethash "status" hash))
   :status-details (gethash "status_details" hash)
   :extras (%copy-file-object-extras hash)))
